services:
  runner:
    image: teikitu-github-runner-win:latest
    cpus: 0.5
    build:
      context: .
      args:
        RUNNER_VERSION: '2.321.0'
    environment:
      GH_TOKEN: ${GH_TOKEN}
      GH_ENTERPRISE: ${GH_ENTERPRISE}
